disabled_rules:
- line_length

opt_in_rules:

included:

excluded:
- Pods
- Rx-MVVMTests
- Rx-MVVMUITests

custom_rules:
      force_https: #HTTPS String이 아니면 경고 발생.
      name: "Force HTTPS over HTTP"
      regex: "((?i)http(?!s))"
      match_kinds: string
      message: "HTTPS should be favored over HTTP"
      severity: warning
