# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rx-MVVM' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Rx-MVVM
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources', '~> 4.0'
pod 'RealmSwift'
pod "RxRealm"

  target 'Rx-MVVMTests' do
    inherit! :search_paths
    # Pods for testing
pod 'RxBlocking'
pod 'RxTest'
  end

  target 'Rx-MVVMUITests' do
    # Pods for testing
  end

end
